// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxesPayments.Data;

#nullable disable

namespace TaxesPayments.Migrations
{
    [DbContext(typeof(TaxesPaymentsContext))]
    [Migration("20230316051547_baip")]
    partial class baip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxesPayments.Models.Taxes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("account")
                        .HasColumnType("int");

                    b.Property<string>("accountComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baip_message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baip_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cashregister_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("errMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partner_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persacc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("point")
                        .HasColumnType("int");

                    b.Property<int>("quickPayId")
                        .HasColumnType("int");

                    b.Property<string>("receipt_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("service")
                        .HasColumnType("int");

                    b.Property<string>("serviceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sum")
                        .HasColumnType("int");

                    b.Property<int>("sum_usluga")
                        .HasColumnType("int");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
